/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package semestralni.prace.database;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import semestralni.prace.Matice;

/**
 *
 * @author Moje
 * 
 * Třída pro zobrazení obsahu databáze v GUI
 * 
 */
public class DBDialog extends javax.swing.JDialog {

    private TableModel myModel;
    private Matice m;
    private Database db;
    
    
    /**
     * Creates new form DBForm
     * 
     * Vytvoří nový JDialog zobraující obsah databáze
     * @throws InstantiationException 
     * @throws ClassNotFoundException
     * @throws SQLException
     * @throws IllegalAccessException  
     */
    public DBDialog() throws InstantiationException, ClassNotFoundException, IllegalAccessException, SQLException {
        initComponents();
            db= new Database();
            db.connect();
            myModel=new TableModel(db.GetConnect());
            jTable1.setModel(myModel);
            jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            //jTable1.getSelectionModel().addListSelectionListener(this);
    }
    
    /**
     *
     * @return
     * 
     * Vrací načtenou matici
     */
    public Matice getM(){
        return m;
    }
    
    /**
     *
     * @return
     * 
     * vrací použitou databázi
     */
    public Database getDb(){
        return db;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

     //   setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Smaž záznam");
        jButton1.setToolTipText("");
        jButton1.setActionCommand("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Načti záznam");
        jButton2.setActionCommand("load");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(125, 125, 125)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-391)/2, (screenSize.height-172)/2, 391, 172);
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            if (jTable1.getSelectedRow()!=-1){
                db.removeRow((jTable1.getSelectedRow()+1));
                myModel.removeRow(jTable1.getSelectedRow());
                myModel.fireTableDataChanged();
                System.out.println("");
            }
           // jTable1.getModel().removeRow(jTable1.getSelectedRow());
        }catch(Exception e){
            System.out.println("Chyba");
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        m = db.loadMatAtRow(jTable1.getSelectedRow()+1);
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration

}
